#!/usr/bin/env python
# vim: et:sw=4:ts=4
# generate a circle in POLY format.
# usage: ./make_circle output.poly radius numberofpoints
#
# e.g. ./make_circle circle.poly 1 1000
# then run ../../papaya
# to calculate the functionals

import sys
from math import pi, sin, cos

fp = open (sys.argv[1], 'w')
radius = float (sys.argv[2])
numberofpoints = int (sys.argv[3])

fp.write ('POINTS\n')
for i in range (numberofpoints):
    ang = 2*pi / numberofpoints * i
    x = radius * cos (ang)
    y = radius * sin (ang)
    fp.write ('%i: %.20e %.20e 0.\n' % (i+1, x, y))

fp.write ('POLYS\n')
fp.write ('1: ')
for i in range (numberofpoints):
    fp.write ('%i ' % (i+1))
fp.write ('<\n')

fp.write ('END\n')

fp.close ()
