#!/usr/bin/env python
# vim: et:sw=4:ts=4
# generate a circle in POLY format.
# usage: mkcircle output.poly radius numberofpoints

import sys
import math

fp = open (sys.argv[1], 'w')
radius = float (sys.argv[2])
numberofpoints = int (sys.argv[3])

fp.write ('POINTS\n')
for i in range (numberofpoints):
    ang = 2*math.pi / numberofpoints * i
    x = radius * math.cos (ang)
    y = radius * math.sin (ang)
    fp.write ('%i: %.20e %.20e 0.\n' % (i, x, y))

fp.write ('POLYS\n')
fp.write ('0: ')
for i in range (numberofpoints):
    fp.write ('%i ' % i)
fp.write ('<\n')

fp.write ('END\n')

fp.close ()

